### ISSUE TITLE
ERROR: Config File doesn't exist

### ISSUE THREAD

**Issue by slavakurilyak** [zuruoke/watermark-removal#11]
When running this code on Google Colab, I get the following:

```
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/neuralgym/ops/layers.py:142: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/neuralgym/callbacks/npz_model_loader.py:31: The name tf.get_variable_scope is deprecated. Please use tf.compat.v1.get_variable_scope instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/neuralgym/ops/gan_ops.py:138: The name tf.layers.Conv2D is deprecated. Please use tf.compat.v1.layers.Conv2D instead.

Traceback (most recent call last):
  File "watermark-removal/main.py", line 26, in <module>
    FLAGS = ng.Config('inpaint.yml')
  File "/usr/local/lib/python3.7/dist-packages/neuralgym/utils/config.py", line 82, in __init__
    assert os.path.exists(filename), "ERROR: Config File doesn't exist."
AssertionError: ERROR: Config File doesn't exist.
```

**Comment by landoncolburn** [comment]
Most likely you're not running config.py from the watermark-removal/ directory. Google Colab runs each command of the form "!command args" in it's own subshell, use %cd watermark-removal instead.
