### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by mobilelifeful** [zuruoke/watermark-removal#3]
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    input_image = preprocess_image(image, args.watermark_type)
  File "/content/watermark-removal/preprocess_image.py", line 42, in preprocess_image
    assert image.shape == preprocessed_mask_image
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by Bellman281** [comment]
I have got the same problem on Colab

**Comment by VIkill33** [comment]
You can just comment line 42 out

**Comment by hallejuyahaha** [comment]
> 

i meet this question too

**Comment by sovrinbloc** [comment]
As @VIkill33 said, you can just comment it out. That worked for me. the  `assert image.shape == preprocessed_mask_image.shape` is a check that apparently doesn't need to be there because it works fine without it.

**Comment by shahmustafa** [comment]
Can anybody comment, on why I am getting this kind of response from model

![rm](https://github.com/zuruoke/watermark-removal/assets/24548277/39266579-c694-4059-a7fa-d75a9a3d3f7f)
