### ISSUE TITLE
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested

### ISSUE THREAD

**Issue by aero8991** [zuruoke/watermark-removal#6]
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    args.checkpoint_dir, from_name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/contrib/framework/python/framework/checkpoint_utils.py", line 81, in load_variable
    return reader.get_tensor(name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested

**Comment by zuruoke** [comment]
could you please follow the guidelines in the README file -> you need to add the location path of model weights or variables to the checkpoint argument

**Comment by jpchupaprecios** [comment]
@aero8991 did you find some solution?
